# nodes interface definition
[[nodes]]
    name = "h1"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.1/24"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.0.254"
[[nodes]]
    name = "h2"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.2/24"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.0.254"
[[nodes]]
    name = "h3"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.3/24"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.0.254"
[[nodes]]
    name = "r1"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = 192.168.1.130/25"
    [[nodes.interfaces]]
    name = "eth1" 
    ipv4 = "192.168.2.130/25"
    [[nodes.interfaces]]
    name = "eth2"
    ipv4 = "192.168.0.254"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.1.129"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.2.129"

# switch
[[nodes]]
    name = "s1"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    [[nodes.interfaces]]
    name = "eth1"
    [[nodes.interfaces]]
    name = "eth2"
    [[nodes.interfaces]]
    name = "eth3"

# middle box
[[nodes]]
    name = "proxy_main"
    type = "middlebox"
    env = "netns"
    app = "squid"
    acl_enabled = 1
    config = """
    access_log /home/leon/neo/examples/configs/squid/log/access.log
    acl SSL_ports port 443    # https
    acl Safe_ports port 80    # http
    acl Safe_ports port 21    # ftp
    acl Safe_ports port 443   # https
    acl Safe_ports port 70    # gopher
    acl Safe_ports port 210   # wais
    acl Safe_ports port 1025-65535  # unregistered ports
    acl Safe_ports port 280   # http-mgmt
    acl Safe_ports port 488   # gss-http
    acl Safe_ports port 591   # filemaker
    acl Safe_ports port 777   # multiling http
    acl CONNECT method CONNECT
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports
    http_access allow localhost manager
    http_access deny manager
    http_access allow localhost
    http_access deny all
    http_port 3128
    access_log stdio:/home/leon/neo/examples/configs/squid/log/access.log squid
    cache_store_log stdio:/home/leon/neo/examples/configs/squid/log/store.log
    cache_log /home/leon/neo/examples/configs/squid/log/cache.log
    coredump_dir /var/spool/squid
    pinger_enable off
    # pid_filename /var/run/squid.pid
    """
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.1.129/25"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "192.168.1.2/25"
    
[[nodes]]
    name = "proxy_backup"
    type = "middlebox"
    env = "netns"
    app = "squid"
    acl_enabled = 1
    config = """
    access_log /home/leon/neo/examples/configs/squid/log/access.log
    acl SSL_ports port 443    # https
    acl Safe_ports port 80    # http
    acl Safe_ports port 21    # ftp
    acl Safe_ports port 443   # https
    acl Safe_ports port 70    # gopher
    acl Safe_ports port 210   # wais
    acl Safe_ports port 1025-65535  # unregistered ports
    acl Safe_ports port 280   # http-mgmt
    acl Safe_ports port 488   # gss-http
    acl Safe_ports port 591   # filemaker
    acl Safe_ports port 777   # multiling http
    acl CONNECT method CONNECT
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports
    http_access allow localhost manager
    http_access deny manager
    http_access allow localhost
    http_access deny all
    http_port 3128
    access_log stdio:/home/leon/neo/examples/configs/squid/log/access.log squid
    cache_store_log stdio:/home/leon/neo/examples/configs/squid/log/store.log
    cache_log /home/leon/neo/examples/configs/squid/log/cache.log
    coredump_dir /var/spool/squid
    pinger_enable off
    # pid_filename /var/run/squid.pid
    """
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.2.129/25"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "192.168.2.2/25"

[[nodes]] 
    name = "gateway"
    type = "middlebox"
    env = "netns"
    app = "netfilter"
    rp_filter = 0
    config = """
    *nat
    :PREROUTING ACCEPT [0:0]
    :INPUT ACCEPT [0:0]
    :OUTPUT ACCEPT [0:0]
    :POSTROUTING ACCEPT [0:0]
    -A POSTROUTING -s 192.168.0.0/24 -o etho0 -j MASQUERADE
    COMMIT
    """
    [[nodes.interface]]
    name = "eth0"
    ipv4 = "192.168.1.1"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "192.168.2.1"

# link 




# policy
[[policies]]
    type = "reachability"
    pkt_dst = "10.0.0.1"
    start_node = "h[123]"
    final_node = "server"
    reachable = true
