[[nodes]]
	nmae = "h0"
	type = "generic"
	[[nodes.interfaces]]
	name = "eth0"
	ipv4 = "192.168.0.2/24
	[[nodes.static_routes]]
	network = "0.0.0.0/0"
	next_hop = "192.168.0.1" 
[[nodes]]
	nmae = "h1"
	type = "generic"
	[[nodes.interfaces]]
	name = "eth0"
	ipv4 = "192.168.0.3/24"
	[[nodes.static_routes]]
	network = "0.0.0.0/0"
	next_hop = "192.168.0.1" 
	
# use transparent proxy here
# the intercept router is combined into the squid proxy, and the intercept functionality should be enabled 
# to route the packet and change the dest address
# 1. kernel functionality for forwarding the packet: net.ipv4.ip_forward = 1
# 2. add redirect packet to squid server: 
#	iptables -t nat -A PERROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3128

# first proxy server
[[nodes]] 
	name = "p0"
	type generic = "middlebox"
	env = "netns"
	app = "squid-proxy"
	config = """
	*forwarding
	iptables -t nat -A PERROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3128
	*squid
  acl SSL_ports port 443    # https
  acl Safe_ports port 80    # http
  acl Safe_ports port 21    # ftp
  acl Safe_ports port 443   # https
  acl Safe_ports port 70    # gopher
  acl Safe_ports port 210   # wais
  acl Safe_ports port 1025-65535  # unregistered ports
  acl Safe_ports port 280   # http-mgmt
  acl Safe_ports port 488   # gss-http
  acl Safe_ports port 591   # filemaker
  acl Safe_ports port 777   # multiling http
  acl CONNECT method CONNECT
  http_access deny !Safe_ports
  http_access deny CONNECT !SSL_ports
  http_access allow localhost manager
  http_access deny manager
  http_access allow localhost
  http_access deny all
  http_port 3128
  access_log stdio:/home/leon/neo/examples/configs/squid/log/access_0.log squid
  cache_store_log stdio:/home/leon/neo/examples/configs/squid/log/store_0.log
  cache_log /home/leon/neo/examples/configs/squid/log/cache_0.log
  pinger_enable off
  pid_filename /home/leon/neo/examples/configs/squid/instance/squid_0.pid
  cache_peer 192.168.3.2 sibling 3128 3130
  acl FTP proto FTP
  acl HTTP proto HTTP 
  acl DayTime time 10:00-18:00
  cache_peer_access 192.168.3.2 allow DayTime 
  cache_peer_access 192.168.3.2 allow FTP
  cache_peer_access 192.168.3.2 allow HTTP
  cache_peer_access 192.168.3.2 deny all
  prefer_direct on
  """
	[[nodes.interfaces]]
	name = "eth0"
	ipv4 = "192.168.1.2/25"
	[[nodes.interfaces]]
	name = "eth1"
	ipv4 = "192.168.1.129/25"
  [[nodes.interfaces]]
  name = "eth2"
  ipv4 = "192.168.3.1/24"
  [[nodes.static_routes]]
  network = "192.168.3.1/24"
  next_hop = "192.168.3.2"
	[[nodes.static_routes]]
	network = "192.168.1.129/25"
	next_hop = "192.168.1.130"
	[[nodes.static_routes]]
	network = "192.168.0.1/24"
	next_hop = "192.168.1.130"
	[[nodes.static_routes]]
	network = "0.0.0.0/0"
	next_hop = "192.168.1.1"
# second proxy
[[nodes]]
	name = "p1"
	type = "middlebox"
	env = "netns"
	app = "squid-proxy"
	config = """
	*forwarding
	iptables -t nat -A PERROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3128
	*squid
  acl SSL_ports port 443    # https
  acl Safe_ports port 80    # http
  acl Safe_ports port 21    # ftp
  acl Safe_ports port 443   # https
  acl Safe_ports port 70    # gopher
  acl Safe_ports port 210   # wais
  acl Safe_ports port 1025-65535  # unregistered ports
  acl Safe_ports port 280   # http-mgmt
  acl Safe_ports port 488   # gss-http
  acl Safe_ports port 591   # filemaker
  acl Safe_ports port 777   # multiling http
  acl CONNECT method CONNECT
  http_access deny !Safe_ports
  http_access deny CONNECT !SSL_ports
  http_access allow localhost manager
  http_access deny manager
  http_access allow localhost
  http_access deny all
  http_port 3128
  access_log stdio:/home/leon/neo/examples/configs/squid/log/access_1.log squid
  cache_store_log stdio:/home/leon/neo/examples/configs/squid/log/store_1.log
  cache_log /home/leon/neo/examples/configs/squid/log/cache_1.log
  pinger_enable off
  pid_filename /home/leon/neo/examples/configs/squid/instance/squid_1.pid
  cache_peer 192.168.3.1 sibling 3128 3130
  acl FTP proto FTP
  acl HTTP proto HTTP 
  acl DayTime time 10:00-18:00
  cache_peer_access 192.168.3.1 allow DayTime 
  cache_peer_access 192.168.3.1 allow FTP
  cache_peer_access 192.168.3.1 allow HTTP
  cache_peer_access 192.168.3.1 deny all
  prefer_direct on
	"""
	[[nodes.interfaces]]
	name = "eth0"
	ipv4 = "192.168.2.2/25"
	[[nodes.interfaces]]
	name = "eth1"
	ipv4 = "192.168.2.129/25"
  [[nodes.interfaces]]
  name = "eth2"
  ipv4 = "192.168.3.2/24"
  [[nodes.static_routes]]
  network = "192.168.3.1/25"
  next_hop = "192.168.3.1"
	[[nodes.static_routes]]
	network = "192.168.2.129/25"
	next_hop = "192.168.2.130"
	[[nodes.static_routes]]
	network = "192.168.0.1/24"
	next_hop = "192.168.2.130"
	[[nodes.static_routes]]
	network = "0.0.0.0/0"
	next_hop = "192.168.2.1"
# firewall configuration, use NAT 
[[nodes]]
    name = "fw"
    type = "middlebox"
    env = "netns"
    app = "netfilter"
    rp_filter = 1
    config = """
    *nat
    :PREROUTING ACCEPT [0:0]
    :INPUT ACCEPT [0:0]
    :OUTPUT ACCEPT [0:0]
    :POSTROUTING ACCEPT [0:0]
    -A POSTROUTING -s 192.168.0.0/22 -o eth0 -j MASQUERADE
    COMMIT
    """
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "208.1.1.102/24"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "192.168.1.1/25"
    [[nodes.interfaces]]
    name = "eth2"
    ipv4 = "192.168.2.1/25"
    [[nodes.static_routes]]
    network = "192.168.1.0/24"
    next_hop = "192.168.1.2"
	[[nodes/static_routes]] 
	network = "192.168.2.0/24"
	next_hop = "192.168.2.2"
	[[nodes.static_routes]] 
	network = "208.1.1.1/24"
	next_hop = "208.1.1.101"
# undeterministic router
[[nodes]]
	name = "r0"
	type = "generic"
	[[nodes.interfaces]]
	name = "eth0"
	ipv4 = "192.168.1.130/25"
	[[node.interfaces]]
	name = "eth1"
	ipv4 = "192.168.2.130/25"
	[[nodes.interfaces]]
	name = "eth2"
	ipv4 = "192.168.0.1/24"
	[[nodes.static_routes]]
	network = "0.0.0.0/0"
	next_hop = "192.168.1.129/25"
	[[noeds.static_routes]]
	network = "0.0.0.0/0"
	next_hop = "192.168.2.129/25"
# switch
[[nodes]]
    name = "s1"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    [[nodes.interfaces]]
    name = "eth1"
    [[nodes.interfaces]]
    name = "eth2"
#server
[[nodes]]
	name = "s0"
	type = "generic"
	[[nodes.interfaces]]
	name = "eth0"
	ipv4 = "208.1.1.101/24"
	[[nodes.static_routes]]
	network = "0.0.0.0/0"
	next_hop = "192.168.0.254"
	
	
# linkage 
[[link]]
	node1 = "s0"
	intf1 = "eth0"
	node2 = "fw"
	intf = "eth0"
[[link]]
	node1 = "fw"
	intf1 = "eth1"
	node2 = "p0"
	intf2 = "eth0"
[[link]] 
	node1 = "fw"
  intf1 = "eth2"
	node2 = "p1"
	intf2 = "eth0"
[[link]] 
	node1 = "p0"
  intf1 = "eth1"
	node2 = "r0"
  intf2 = "eth0"
[[link]]
	node1 = "p1"
  intf1 = "eth1"
	node2 = "r0"
  intf2 = "eth1"
[[link]] 
  node1 = "p0"
  intf1 = "eth2"
  node2 = "p1"
  intf2 = "eth2"
[[link]] 
	node1 = "r0" 
  intf1 = "eth2"
	node2 = "s1"
  intf2 = "eth0"
[[link]]
	node1 = "s1"
  intf1 = "eth1"
	node2 = "h0"
  intf2 = "eth0"
[[link]]
	node1 = "s1"
  intf1 = "eth2"
	node2 = "h1"
  intf2 = "eth0"

# Policy:
#   1. Requested host should always be hit in cache among the proxies

[[policies]]
    type = "hitonseen"
    host_dest = "http://www.columbia.edu/~fdc/sample.html"
    start_node = "h[01]"
    final_node = "server"
[[policies]]
    type = "reachability"
    pkt_dst = ""
    start_node = ""
    final_node = ""
    reachable = true

