codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "50...100"
  status:
    project:
      default:
        target: auto
        threshold: null
        base: auto
    patch:
      default:
        target: auto
        threshold: null
        base: auto
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "third_party"
  - "test"
