language: cpp
dist: xenial
matrix:
  include:
    - name: "GCC Test"
      os: linux
      addons:
        apt:
          packages:
            - gcc
      env:
        - CC = 'gcc'
        - CXX = 'g++'
        - GCOV = 'gcov'
        - TRAVIS_JOB_NAME = 'GCC Test'
    - name: "Clang Test"
      os: linux
      addons:
        apt:
          packages:
            - clang
            - llvm
      env:
        - CC = 'clang'
        - CXX = 'clang++'
        - GCOV = 'llvm-cov gcov'
        - TRAVIS_JOB_NAME = 'Clang Test'

install:
  - ./setup.sh
script:
  - ./test/all.sh
