language: cpp
dist: focal
matrix:
  include:
    - name: "GCC Test"
      os: linux
      addons:
        apt:
          packages:
            - gcc
      env:
        - CC = 'gcc'
        - CXX = 'g++'
        - TRAVIS_JOB_NAME = 'GCC Test'
    - name: "Clang Test"
      os: linux
      addons:
        apt:
          packages:
            - clang
      env:
        - CC = 'clang'
        - CXX = 'clang++'
        - TRAVIS_JOB_NAME = 'Clang Test'

install:
  - ./depends/setup.sh
script:
  - ./test/all.sh
