[[nodes]]
    name = "h0"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.1/30"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.0.2"
[[nodes]]
    name = "h1"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.1.1/30"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.1.2"
[[nodes]]
    name = "h2"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.2.1/30"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.2.2"
[[nodes]]
    name = "r0"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.2/30"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "192.168.1.2/30"
    [[nodes.interfaces]]
    name = "eth2"
    ipv4 = "192.168.2.2/30"
[[links]]
    node1 = "h0"
    intf1 = "eth0"
    node2 = "r0"
    intf2 = "eth0"
[[links]]
    node1 = "h1"
    intf1 = "eth0"
    node2 = "r0"
    intf2 = "eth1"
[[links]]
    node1 = "h2"
    intf1 = "eth0"
    node2 = "r0"
    intf2 = "eth2"

[openflow]
    [[openflow.updates]]
    node = "r0"
    network = "8.8.8.0/24"
    outport = "eth1"
    [[openflow.updates]]
    node = "r0"
    network = "8.8.8.8/32"
    outport = "eth2"

[[policies]]
    type = "waypoint"
    waypoint = "h1"
    pass_through = false
    [policies.communication]
    protocol = "tcp"
    pkt_dst = "8.8.8.8"
    dst_port = 80
    start_node = "h0"
[[policies]]
    type = "waypoint"
    waypoint = "h2"
    pass_through = false
    [policies.communication]
    protocol = "tcp"
    pkt_dst = "8.8.8.8"
    dst_port = 80
    start_node = "h0"
