[[nodes]]
    name = "h1"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.1/24"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "192.168.1.1/24"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.0.2"
[[nodes]]
    name = "h2"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "10.0.0.1/24"
    [[nodes.static_routes]]
    network = "192.168.0.0/23"
    next_hop = "10.0.0.2"
[[nodes]]
    name = "s1"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    [[nodes.interfaces]]
    name = "eth1"
[[nodes]]
    name = "s2"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    [[nodes.interfaces]]
    name = "eth1"
[[nodes]]
    name = "fw"
    type = "middlebox"
    driver = "netfilter-netns"
    config = """
    *nat
    :PREROUTING ACCEPT [0:0]
    :INPUT ACCEPT [0:0]
    :OUTPUT ACCEPT [0:0]
    :POSTROUTING ACCEPT [0:0]
    -A POSTROUTING -s 192.168.0.0/23 -o eth2 -j MASQUERADE
    COMMIT

    *filter
    :INPUT DROP [0:0]
    :FORWARD DROP [0:0]
    :OUTPUT ACCEPT [0:0]
    -A FORWARD -i eth0 -j ACCEPT
    -A FORWARD -i eth1 -j ACCEPT
    -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    COMMIT
    """
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.2/24"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "192.168.1.2/24"
    [[nodes.interfaces]]
    name = "eth2"
    ipv4 = "10.0.0.2/24"

[[links]]
    node1 = "h1"
    intf1 = "eth0"
    node2 = "s1"
    intf2 = "eth0"
[[links]]
    node1 = "h1"
    intf1 = "eth1"
    node2 = "s2"
    intf2 = "eth0"
[[links]]
    node1 = "s1"
    intf1 = "eth1"
    node2 = "fw"
    intf2 = "eth0"
[[links]]
    node1 = "s2"
    intf1 = "eth1"
    node2 = "fw"
    intf2 = "eth1"
[[links]]
    node1 = "fw"
    intf1 = "eth2"
    node2 = "h2"
    intf2 = "eth0"

# Policy:
#   1. Outgoing packets are always allowed.
#   2. Incoming packets are always denied, unless they're replies to past
#      requests.

[[policies]]
    type = "reachability"
    pkt_src = "192.168.1.1"
    pkt_dst = "10.0.0.1"
    start_node = "h1"
    final_node = "h2"
    reachable = true
[[policies]]
    type = "stateful-reachability"
    pkt_src = "10.0.0.1"
    pkt_dst = "192.168.0.1"
    start_node = "h2"
    final_node = "h1"
    reachable = false
    stateful_reachable = true
    [policies.prerequisite]
    type = "waypoint"
    pkt_src = "192.168.0.1"
    pkt_dst = "10.0.0.1"
    start_node = "h1"
    waypoint = "fw"
    pass_through = true
