[[nodes]]
    name = "string"
    type = "generic" or "middlebox"
    [[nodes.interfaces]]        # optional
    name = "string"
    ipv4 = "x.x.x.x/x"          # optional
    vlans = [1, 3, 6, 100]      # optional
    [[nodes.static_routes]]     # optional
    network = "x.x.x.x/x"
    next_hop = "x.x.x.x"
    adm_dist = 1                # optional (0..255), default: 1
    weight = 1                  # optional, default: 1
    [[nodes.installed_routes]]  # optional
    network = "x.x.x.x/x"
    next_hop = "x.x.x.x"
    adm_dist = 255              # optional (0..255), default: 255
[[nodes]]
    name = "string"
    type = "middlebox"
    driver = "netns"
    middlebox = "netfilter"
    config = ".*"

# undirected (only need to specify once for each bidirectional link)
[[links]]
    node1 = "name"
    intf1 = "name"
    node2 = "name"
    intf2 = "name"

[[policies]]
    type = "reachability"
    pkt_dst = "x.x.x.x(/x)"
    start_node = "node name regex"
    final_node = "node name regex"
    reachable = true or false
[[policies]]
    type = "waypoint"
    pkt_dst = "x.x.x.x(/x)"
    start_node = "node name regex"
    waypoint = "node name regex"
    pass_through = true or false
[[policies]]
    type = "stateful-reachability"
    pkt_dst = "x.x.x.x(/x)"
    start_node = "node name regex"
    final_node = "node name regex"
    reachable = true or false
    [policies.prerequisite]
    type = "reachability"
    pkt_dst = "x.x.x.x(/x)"
    start_node = "node name regex"
    final_node = "node name regex"
    reachable = true or false
[[policies]]
################## TODO
    type = "stateful-reachability"
    pkt_dst = "x.x.x.x(/x)"
    start_node = "node name regex"
    final_node = "node name regex"
    reachable = true or false
    [policies.prerequisite]
    type = "waypoint"
    pkt_dst = "x.x.x.x(/x)"
    start_node = "node name regex"
    waypoint = "node name regex"
    pass_through = true or false
