[[nodes]]
    name = "h1"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.1/24"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.0.254"
[[nodes]]
    name = "h2"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.2/24"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.0.254"
[[nodes]]
    name = "h3"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.3/24"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.0.254"
[[nodes]]
    name = "s1"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    [[nodes.interfaces]]
    name = "eth1"
    [[nodes.interfaces]]
    name = "eth2"
    [[nodes.interfaces]]
    name = "eth3"
[[nodes]]
    name = "r1"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.0.254/24"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "192.168.1.254/24"
    [[nodes.static_routes]]
    network = "0.0.0.0/0"
    next_hop = "192.168.1.1"
[[nodes]]
    name = "lb"
    type = "middlebox"
    env = "netns"
    app = "ipvs"
    timeout = 1000
    config = """
-A -t 192.168.1.1:80 -s rr
-a -t 192.168.1.1:80 -r 10.0.0.1:80 -m
-a -t 192.168.1.1:80 -r 10.0.0.2:80 -m
-a -t 192.168.1.1:80 -r 10.0.0.3:80 -m
"""
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "192.168.1.1/24"
    [[nodes.interfaces]]
    name = "eth1"
    ipv4 = "10.0.0.254/24"
    [[nodes.static_routes]]
    network = "192.168.0.0/16"
    next_hop = "192.168.1.254"
[[nodes]]
    name = "s2"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    [[nodes.interfaces]]
    name = "eth1"
    [[nodes.interfaces]]
    name = "eth2"
    [[nodes.interfaces]]
    name = "eth3"
[[nodes]]
    name = "server1"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "10.0.0.1/24"
    [[nodes.static_routes]]
    network = "192.168.0.0/16"
    next_hop = "10.0.0.254"
[[nodes]]
    name = "server2"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "10.0.0.2/24"
    [[nodes.static_routes]]
    network = "192.168.0.0/16"
    next_hop = "10.0.0.254"
[[nodes]]
    name = "server3"
    type = "generic"
    [[nodes.interfaces]]
    name = "eth0"
    ipv4 = "10.0.0.3/24"
    [[nodes.static_routes]]
    network = "192.168.0.0/16"
    next_hop = "10.0.0.254"

[[links]]
    node1 = "s1"
    intf1 = "eth1"
    node2 = "h1"
    intf2 = "eth0"
[[links]]
    node1 = "s1"
    intf1 = "eth2"
    node2 = "h2"
    intf2 = "eth0"
[[links]]
    node1 = "s1"
    intf1 = "eth3"
    node2 = "h3"
    intf2 = "eth0"
[[links]]
    node1 = "s1"
    intf1 = "eth0"
    node2 = "r1"
    intf2 = "eth0"
[[links]]
    node1 = "lb"
    intf1 = "eth0"
    node2 = "r1"
    intf2 = "eth1"
[[links]]
    node1 = "lb"
    intf1 = "eth1"
    node2 = "s2"
    intf2 = "eth0"
[[links]]
    node1 = "server1"
    intf1 = "eth0"
    node2 = "s2"
    intf2 = "eth1"
[[links]]
    node1 = "server2"
    intf1 = "eth0"
    node2 = "s2"
    intf2 = "eth2"
[[links]]
    node1 = "server3"
    intf1 = "eth0"
    node2 = "s2"
    intf2 = "eth3"

# Policy:
#   1. Outgoing packets are always allowed. (This should fail due to the
#      misconfiguration of fw.)
#   2. Incoming packets are always denied, except for 3.
#   3. Incoming replies to past requests are allowed.

[[policies]]
    type = "reachability"
    protocol = "http"
    pkt_dst = "192.168.1.1"
    start_node = "h[123]"
    final_node = "server3"
    reachable = true
