name: main
on: [push]
jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: ${GITHUB_WORKSPACE}/depends/setup.sh

  astyle-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: ${GITHUB_WORKSPACE}/test/astyle.sh

  default-build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: >-
          cmake -B ${GITHUB_WORKSPACE}/build -S ${GITHUB_WORKSPACE}
            -DCMAKE_BUILD_TYPE=Release
            -DENABLE_TESTS=ON
            -DENABLE_COVERAGE=ON
      - run: cmake --build ${GITHUB_WORKSPACE}/build
      - run: ctest
        working-directory: ${GITHUB_WORKSPACE}/build

  clang-build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: >-
          cmake -B ${GITHUB_WORKSPACE}/clang-build -S ${GITHUB_WORKSPACE}
            -DCMAKE_BUILD_TYPE=Release
            -DENABLE_TESTS=ON
            -DENABLE_COVERAGE=ON
            -DCMAKE_C_COMPILER=clang
            -DCMAKE_CXX_COMPILER=clang++
      - run: cmake --build ${GITHUB_WORKSPACE}/clang-build
      - run: ctest
        working-directory: ${GITHUB_WORKSPACE}/clang-build

  coverage-report:
    needs: default-build
    runs-on: ubuntu-latest
    steps:
      - uses: codecov/codecov-action@v1
        with:
          directory: ${GITHUB_WORKSPACE}/build
          gcov_args: '-l'
          fail_ci_if_error: true
          verbose: true
