name: Test
on: [push, pull_request]
jobs:

  astyle-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install astyle
      - run: ${GITHUB_WORKSPACE}/test/astyle.sh

  build:
    needs: astyle-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: ${GITHUB_WORKSPACE}/depends/setup.sh
      - run: >
          cmake -B ${GITHUB_WORKSPACE}/build -S ${GITHUB_WORKSPACE}
            -DCMAKE_BUILD_TYPE=Release
            -DENABLE_TESTS=ON
            -DENABLE_COVERAGE=ON
            -DCMAKE_C_COMPILER=${{ matrix.cc }}
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
      - run: cmake --build ${GITHUB_WORKSPACE}/build
      - run: ctest
        working-directory: ${GITHUB_WORKSPACE}/build
      - uses: codecov/codecov-action@v1
        with:
          directory: ${GITHUB_WORKSPACE}/build
          gcov_args: '-l'
          fail_ci_if_error: true
          verbose: true
