name: test
on: [push, pull_request]
jobs:

  astyle-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install astyle
      - run: ./test/astyle.sh

  build:
    needs: astyle-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: ./depends/setup.sh
      - run: >
          cmake -B build -S .
          -DCMAKE_BUILD_TYPE=Release
          -DENABLE_TESTS=ON
          -DENABLE_COVERAGE=ON
          -DCMAKE_C_COMPILER=${{ matrix.cc }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
      - run: cmake --build build
      - run: ctest
        working-directory: ./build
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          gcov_args: '-l'
        if: matrix.cc == 'gcc'
